import filterPokemon from '../src/filter-pokemon.js';
const test = QUnit.test;

QUnit.module('filter test');

const pokemon = [
    {
        'pokemon': 'bulbasaur',
        'id': 1,
        'species_id': 1,
        'height': 7,
        'weight': 69,
        'base_experience': 64,
        'type_1': 'grass',
        'type_2': 'poison',
        'attack': 49,
        'defense': 49,
        'hp': 45,
        'special_attack': 65,
        'special_defense': 65,
        'speed': 45,
        'ability_1': 'overgrow',
        'ability_2': 'NA',
        'ability_hidden': 'chlorophyll',
        'color_1': '#78C850',
        'color_2': '#A040A0',
        'color_f': '#81A763',
        'egg_group_1': 'monster',
        'egg_group_2': 'plant',
        'url_image': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',
        'generation_id': 1,
        'evolves_from_species_id': 'NA',
        'evolution_chain_id': 1,
        'shape_id': 8,
        'shape': 'quadruped',
        'pokebase': 'bulbasaur',
        'pokedex': 'http://www.pokemon.com/us/pokedex/bulbasaur'
    },
    {
        'pokemon': 'charizard',
        'id': 7,
        'species_id': 6,
        'height': 17,
        'weight': 905,
        'base_experience': 240,
        'type_1': 'fire',
        'type_2': 'flying',
        'attack': 84,
        'defense': 78,
        'hp': 78,
        'special_attack': 109,
        'special_defense': 85,
        'speed': 100,
        'ability_1': 'blaze',
        'ability_2': 'NA',
        'ability_hidden': 'solar-power',
        'color_1': '#F08030',
        'color_2': '#A890F0',
        'color_f': '#DE835E',
        'egg_group_1': 'monster',
        'egg_group_2': 'dragon',
        'url_image': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png',
        'generation_id': 1,
        'evolves_from_species_id': '5',
        'evolution_chain_id': 2,
        'shape_id': 6,
        'shape': 'upright',
        'pokebase': 'charizard',
        'pokedex': 'http://www.pokemon.com/us/pokedex/charizard'
    },
    {
        'pokemon': 'blastoise',
        'id': 12,
        'species_id': 9,
        'height': 16,
        'weight': 855,
        'base_experience': 239,
        'type_1': 'water',
        'type_2': 'NA',
        'attack': 83,
        'defense': 100,
        'hp': 79,
        'special_attack': 85,
        'special_defense': 105,
        'speed': 78,
        'ability_1': 'torrent',
        'ability_2': 'NA',
        'ability_hidden': 'rain-dish',
        'color_1': '#6890F0',
        'color_2': 'NA',
        'color_f': 'NA',
        'egg_group_1': 'monster',
        'egg_group_2': 'water1',
        'url_image': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png',
        'generation_id': 1,
        'evolves_from_species_id': '8',
        'evolution_chain_id': 3,
        'shape_id': 6,
        'shape': 'upright',
        'pokebase': 'blastoise',
        'pokedex': 'http://www.pokemon.com/us/pokedex/blastoise'
    },
    {
        'pokemon': 'psyduck',
        'id': 60,
        'species_id': 54,
        'height': 8,
        'weight': 196,
        'base_experience': 64,
        'type_1': 'water',
        'type_2': 'NA',
        'attack': 52,
        'defense': 48,
        'hp': 50,
        'special_attack': 65,
        'special_defense': 50,
        'speed': 55,
        'ability_1': 'damp',
        'ability_2': 'cloud-nine',
        'ability_hidden': 'swift-swim',
        'color_1': '#6890F0',
        'color_2': 'NA',
        'color_f': 'NA',
        'egg_group_1': 'water1',
        'egg_group_2': 'ground',
        'url_image': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png',
        'generation_id': 1,
        'evolves_from_species_id': 'NA',
        'evolution_chain_id': 23,
        'shape_id': 6,
        'shape': 'upright',
        'pokebase': 'psyduck',
        'pokedex': 'http://www.pokemon.com/us/pokedex/psyduck'
    }
];

test('filters for pokemon by type_1', assert => {
    //arrange
    let filter = { type_1: 'water' };
    const expected = [
        {
            'pokemon': 'blastoise',
            'id': 12,
            'species_id': 9,
            'height': 16,
            'weight': 855,
            'base_experience': 239,
            'type_1': 'water',
            'type_2': 'NA',
            'attack': 83,
            'defense': 100,
            'hp': 79,
            'special_attack': 85,
            'special_defense': 105,
            'speed': 78,
            'ability_1': 'torrent',
            'ability_2': 'NA',
            'ability_hidden': 'rain-dish',
            'color_1': '#6890F0',
            'color_2': 'NA',
            'color_f': 'NA',
            'egg_group_1': 'monster',
            'egg_group_2': 'water1',
            'url_image': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png',
            'generation_id': 1,
            'evolves_from_species_id': '8',
            'evolution_chain_id': 3,
            'shape_id': 6,
            'shape': 'upright',
            'pokebase': 'blastoise',
            'pokedex': 'http://www.pokemon.com/us/pokedex/blastoise'
        },
        {
            'pokemon': 'psyduck',
            'id': 60,
            'species_id': 54,
            'height': 8,
            'weight': 196,
            'base_experience': 64,
            'type_1': 'water',
            'type_2': 'NA',
            'attack': 52,
            'defense': 48,
            'hp': 50,
            'special_attack': 65,
            'special_defense': 50,
            'speed': 55,
            'ability_1': 'damp',
            'ability_2': 'cloud-nine',
            'ability_hidden': 'swift-swim',
            'color_1': '#6890F0',
            'color_2': 'NA',
            'color_f': 'NA',
            'egg_group_1': 'water1',
            'egg_group_2': 'ground',
            'url_image': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png',
            'generation_id': 1,
            'evolves_from_species_id': 'NA',
            'evolution_chain_id': 23,
            'shape_id': 6,
            'shape': 'upright',
            'pokebase': 'psyduck',
            'pokedex': 'http://www.pokemon.com/us/pokedex/psyduck'
        }
    ];
    //act
    let filtered = filterPokemon(pokemon, filter);
    //assert
    assert.deepEqual(filtered, expected);
});

test('filter returns matching name', assert => {
//arrange
    let filter = { pokemon: 'psyduck' };
    
    let expected = [
        {
            'pokemon': 'psyduck',
            'id': 60,
            'species_id': 54,
            'height': 8,
            'weight': 196,
            'base_experience': 64,
            'type_1': 'water',
            'type_2': 'NA',
            'attack': 52,
            'defense': 48,
            'hp': 50,
            'special_attack': 65,
            'special_defense': 50,
            'speed': 55,
            'ability_1': 'damp',
            'ability_2': 'cloud-nine',
            'ability_hidden': 'swift-swim',
            'color_1': '#6890F0',
            'color_2': 'NA',
            'color_f': 'NA',
            'egg_group_1': 'water1',
            'egg_group_2': 'ground',
            'url_image': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png',
            'generation_id': 1,
            'evolves_from_species_id': 'NA',
            'evolution_chain_id': 23,
            'shape_id': 6,
            'shape': 'upright',
            'pokebase': 'psyduck',
            'pokedex': 'http://www.pokemon.com/us/pokedex/psyduck'
        }];
//act
    const result = filterPokemon(pokemon, filter);
//assert
    assert.deepEqual(result, expected);
});